## Final project checklist

0. Optional: Reinterpret the mathematical form of the initial model in terms of a system that you find more interesting. (suggested deadline: Nov 10)
    - For example, you might be more interested in polar bears, not deer.
1. Analyze the stability and fixed points of the initial model. (suggested deadline: Nov 10/11)
2. Answer the preliminary question.  (suggested deadline: Nov 13-15)
    - Note that there is no simple answer to this question, but instead will depend on how you have chosen to answer it. It is an open ended question.
    - While answering the question you should propose reasonable default values for the parameters.
3. Propose a question (or questions) of your own.  (suggested deadline: Nov 20)
    - Answering these questions should require an extension of the initial model.
    - Consider adding parameters that will represent new conditions, and then asking questions about how the dynamics will respond to changes in the parameters.
4. Check to see if your proposed model is sensible by numerically and/or mathematically analyzing it.  (suggested deadline: Nov 20)
    - If the model is not sensible (a common situation), return to step 3.
5. Answer your own question.  (suggested deadline: Nov 27)
6. Write up your findings in the following format (using Rmarkdown).  (deadline:  Dec 2)
    - A short introduction (~ 1 paragraph) in which you pose your questions as extentions to the basic model.
    - A description of your model extension.
    - A description of what analyses you will use to answer your
      questions (including the original question).
    - A description of your your results *that are useful for
      supporting your conclusions*, including your conclusions about
      the original question, and your fixed-point stability analysis for both
	  the original model and your extension.
    - A short concluding paragraph summarizing your answers and what you would try next.
    - List any references you may have used.
    - A technical appendix, which you should refer to in your results section, giving code and mathematical derivations that are required to reproduce your results.
    
    
## Final project marking rubric

This rubric relates to your extensions of the initial model.  Your work on the preliminary question and initial model will be graded similarly to the homework assignments.

<li><strong>A</strong>: Either a thorough analysis of a moderately complex/sophisticated model, or analyses of several simpler versions of the model. At least some analytical results, possibly for a simplified version of the model,
are presented, along with at least some computational results, possibly
for a more complex version of the model. The problem and the model are
clearly described. The results are illustrated with sensible plots. If
the model used is reconstructed from a paper, then some
sensible/interesting extension of the original model is included.  The report is clearly and succinctly written.
</li>

<li><strong>
B</strong>: A thorough analysis of a simple model.  May include only analytical
or only computational results, but these results must be solid. The
problem and the analysis are still clearly described. A reconstruction
of a complex or several-part model from the literature without any
extensions or new material would fall in this category.
</li>

<li><strong>
  C:</strong>
A partial analysis of a simple model.  The basic information about
the model is included, but either the model is extremely simple (and no
variants or more complex versions are attempted) or the analysis is
limited -- for example, implementing a simple model in R and showing a
single run of the model, without exploring the results (dependence on
parameter values, variations of the model, etc.)
</li>

<p>
  The example exercises in the book would probably get a B or a C,
depending on the presentation and level of detail.
</p>

<li><strong>
  D/F:</strong> little evidence of effort. Did not come to David or I for help with formulating or solving the model (it's fine not to come for help if you
don't need it, but I will look much more kindly on otherwise lacking
projects if I know that you really tried!)
</li>
</ul>

## Final project mark breakdown

Overall presentation [20]%
For example,
- equations should be in LaTeX.
- headings for organizing the discussion.
- good communication, which means clearly and succinctly posing the questions in the introduction, answering them in the conclusion.
- commented R code.

Analytical analysis of the system: [30]%
Full marks if analysis is correct and relatively exhaustive (look at
all fixed points, study type of stability, etc).

Numerical implementation: [30]%
- Reasonable implementation in R (e.g. x<-1:10 not x[1]=1, x[2]=2, ...)
- Commented code
- Double check that the simulations do not contradict the analysis
(typically with a combination of a plot and formal test like printing
the actual difference as time gets large)
- Look at various assumptions on parameter values and
model structure.

Overall project complexity: [20]%
Differentiate between simple and more challenging model extensions. 
