---
title: "Introduction to R"
output: html_document
---

## Exercise 6.6: Recreate Figure 1.5 on pp. 15 of Mooney and Swift's book

```{r, fig.width=6, fig.height=4}
## shortcut for setting several values at once
N_best <- N_medium <- N_worst <- numeric(15)

## keep all values in a single named vector
L <- c(best = 0.0194, medium = -0.0324, worst = -0.0382)
startval <- 100
N_best[1] <- N_medium[1] <- N_worst[1] <- startval
for (i in 2:15) {
  N_best[i] <- N_best[i-1] * (1 + L["best"])
  N_medium[i] <- N_medium[i-1] * (1 + L["medium"])
  N_worst[i] <- N_worst[i-1] * (1 + L["worst"])
}
tvec <- 0:14

## alternatively:
N_best <- startval * (1 + L["best"])^tvec

## and so forth
par(mar = c(5, 4, 2, 8) + 0.1)     ## enlarge right margin for legend
leg_inset <- -0.38
matplot(tvec, cbind(N_best, N_medium, N_worst),
        type = "o",           ## lines going through points
        pch = c(18, 15, 17),      ## try to match point types from orig.
        cex = c(1.5, 1, 1),       ## homogeneous point sizes
        col = "black", lty = 1,  
        ylim = c(0, 140),      ## set y limit
        xaxs = "i", yaxs = "i",  ## no extra space at edges of axes
        las = 1,              ## turn y-axis labels horizontal
        tcl = -0.25,
        xaxt = "n",
        ylab = "Population", xlab = "Years")
legend("right", c("Best", "Medium", "Worst"),
       inset = leg_inset,         ## move legend outside figure
       xpd = NA,              ## avoid clipping at edge of figure region
       pch = c(18, 15, 17), lty = 1,
       pt.cex = c(1.5, 1, 1),
       merge = TRUE)          ## overlay points and lines
axis(1, at = seq(0, 14, 2), labels = seq(0, 14, 2), 
     tcl = 0, xaxp = c(0, 14, 14))
axis(1, at = 0:14, labels = FALSE, tcl = 0.25)
axis(1, at = 0:14, labels = FALSE, tcl = -0.25)
axis(2, labels = FALSE, tcl = 0.25)
```

Here's an alternative using `plot` instead of `matplot` (probably more like what the students will do),
```{r, fig.width=6, fig.height=4}
N <- list(best = N_best,
          medium = N_medium,
          worst = N_worst)
tvec <- 0:14

par(mar = c(5, 4, 2, 8) + 0.1)
plot(range(tvec), c(0, 140),
     type = "n", las = 1,
     ylab = "Population",
     xlab = "Years",
     tcl = -0.25,
     xaxt = "n",
     xaxs = "i", yaxs = "i")
pchs <- c(18, 15, 17)
cexs <- c(1.5, 1, 1)       ## homogeneous point sizes
for(i in 1:3) {
    lines(tvec, N[[i]])
    points(tvec, N[[i]], pch = pchs[i], cex = cexs[i])
}
legend("right", c("Best", "Medium", "Worst"),
       inset = -0.38,         ## move legend outside figure
       xpd = NA,              ## avoid clipping at edge of figure region
       pch = c(18, 15, 17), lty = 1,
       pt.cex = c(1.5, 1, 1),
       merge = TRUE)          ## overlay points and lines
axis(1, at = seq(0, 14, 2), labels = seq(0, 14, 2), 
     tcl = 0, xaxp = c(0, 14, 14))
axis(1, at = 0:14, labels = FALSE, tcl = 0.25)
axis(1, at = 0:14, labels = FALSE, tcl = -0.25)
axis(2, labels = FALSE, tcl = 0.25)
```


### Exercise 9.1
```{r}
seq(1, 13, by = 4)
## I prefer to name "by" explicitly, but not necessary or
seq(1, by = 4, length = 4)
seq(1, 5, by = 0.2)
```


### Exercise 9.2
```{r}
z <- c(1, 3, 5, 7, 9, 11) ## set value of z
## or: z=seq(1,11,by=2)
z[c(2, 1, 3)]
```

### Exercise 9.4
```{r}
r <- 0.5
n <- 10
G  <-  r^(0:n)
sum(G)
1/(1-r)
n <- 50
sum(r^(0:n))
2-sum(r^(0:n))  ## not EXACTLY equal
```
Or, if the students take the *one-line* instruction to the extreme,
```{r}
sum(0.5^(0:10))
sum(0.5^(0:50))
```

### Exercise 9.7
```{r}
## set seed and create vector:
set.seed(273)
x <- runif(20)
which(x < mean(x))
```
or
```{r}
p <- 1:length(x)
p[x < mean(x)]
```

